name: .NET

on:
  push:
    branches: [ nuget ]
  pull_request:
    branches: [ nuget ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: NuGet
        run: dotnet nuget push ./src/DapperSupplement/bin/Release/Jumboly.DapperSupplement.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
